{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "databend-meta.fullname" . }}
  labels:
    {{- include "databend-meta.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "databend-meta.fullname" . }}
  selector:
    matchLabels:
      {{- include "databend-meta.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.podMonitor.port }}
      path: /v1/metrics
{{- end }}
