{
 "title": "Databend Meta Runtime",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(metasrv_server_is_leader)"
    }
   ]
  },
  {
   "title": "Leader (Node ID)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(metasrv_server_current_leader_id)"
    }
   ]
  },
  {
   "title": "Total Watchers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(metasrv_server_watchers)" }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Last Log Index",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "metasrv_server_last_log_index", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Last Seq",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "targets": [
    { "expr": "metasrv_server_last_seq", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Term",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "targets": [
    { "expr": "metasrv_server_current_term", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Proposals Applied (Number per second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(metasrv_server_proposals_applied[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposals Pending (Number per second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(metasrv_server_proposals_pending[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "metasrv_server_leader_changes (Number per second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(metasrv_server_leader_changes{}[1m]) /60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current leader id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(metasrv_server_current_leader_id)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Raft Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Active Peers Connection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(metasrv_raft_network_active_peers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recv Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(metasrv_meta_network_recv_bytes{}[$__rate_interval]))",
     "legendFormat": "{{pod}} {{from}}"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(metasrv_raft_network_sent_bytes{}[$__rate_interval]))",
     "legendFormat": "{{pod}} {{to}}"
    }
   ]
  },
  { "title": "Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Snapshot Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(metasrv_raft_network_snapshot_recv_success[$__rate_interval]))",
     "legendFormat": "{{pod}} recv"
    },
    {
     "expr": "sum(rate(metasrv_raft_network_snapshot_send_success[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} send"
    }
   ]
  },
  {
   "title": "Snapshot Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(metasrv_raft_network_snapshot_send_failures[$__rate_interval]))",
     "legendFormat": "{{pod}} recv"
    },
    {
     "expr": "rate(metasrv_raft_network_snapshot_recv_failures[$__rate_interval])",
     "legendFormat": "{{pod}} send"
    }
   ]
  },
  {
   "title": "Snapshot Inflights",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 46 },
   "targets": [
    {
     "expr": "sum(metasrv_raft_network_snapshot_send_inflights{})",
     "legendFormat": "{{pod}} send"
    },
    {
     "expr": "metasrv_raft_network_snapshot_recv_inflights{}",
     "legendFormat": "{{pod}} recv"
    }
   ]
  },
  {
   "title": "Snapshot Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum(metasrv_raft_network_snapshot_sent_seconds_sum)",
     "legendFormat": "{{pod}} {{from}}"
    },
    {
     "expr": "metasrv_raft_network_snapshot_recv_seconds_sum",
     "legendFormat": "{{pod}} {{from}}"
    }
   ]
  },
  {
   "title": "Applying Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 46 },
   "targets": [
    {
     "expr": "sum(metasrv_server_applying_snapshot)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}