{
 "title": "Databend Query Runtime",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "tenant", "label": "tenant", "query": { "query": "label_values(tenant)" } }
  ]
 },
 "panels": [
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Start",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_start_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Success",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_success_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Failed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_failed_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(databend_query_duration_ms_bucket[5m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Result Rows",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_result_rows_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Result Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_result_bytes_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(databend_session_connect_numbers_total{}[1m])) by (cluster_name)",
       "legendFormat": "{{ cluster_name }} connected"
      },
      {
       "expr": "sum(rate(session_close_numbers{}[1m])) by (cluster_name)",
       "legendFormat": "{{ cluster_name }} closed"
      }
     ]
    },
    {
     "title": "Query Scan Partitions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_scan_partitions_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Total Partitions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_total_partitions_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Scan Rows",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_scan_rows_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Scan Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_scan_bytes_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Scan IO Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_scan_io_bytes_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Scan IO Bytes Cost",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(databend_query_scan_io_bytes_cost_ms_bucket[$__rate_interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Write Rows",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_write_rows_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Write Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_write_rows_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Write IO Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(databend_query_write_io_bytes_total[$__rate_interval])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Write IO Bytes Cost",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(databend_query_write_io_bytes_cost_ms{quantile=\"0.99\"}) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Meta GRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meta grpc requests/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(databend_meta_grpc_client_request_success_total{}[60s]) / 60)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(databend_meta_grpc_client_request_fail_total[60s])) by (pod) > 0",
       "legendFormat": "{{ pod }} failed"
      }
     ]
    },
    {
     "title": "Meta grpc requests inflight",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(databend_meta_grpc_client_request_inflight)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(meta_grpc_client_request_fail{namespace=\"tn-$tenant\"}[60s])) by (pod) > 0",
       "legendFormat": "{{ pod }} failed"
      }
     ]
    },
    {
     "title": "Meta grpc per Minute",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(databend_meta_grpc_client_request_success_total{}[1m])) by (request)",
       "legendFormat": "{{ request }}"
      }
     ]
    },
    {
     "title": "Meta grpc P90",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(databend_meta_grpc_client_request_duration_ms_bucket[5m])) by (le))  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Meta grpc P75",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(databend_meta_grpc_client_request_duration_ms_bucket[5m])) by (le))  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Meta grpc P50",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(databend_meta_grpc_client_request_duration_ms_bucket[5m])) by (le))  ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Opendal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Opendal requests P99",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(databend_opendal_request_duration_seconds_bucket[5m])) by (le))  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Opendal Requests/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(databend_opendal_requests_total[1m]) / 60)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "(s3) opendal_bytes_total/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(databend_opendal_bytes_total{service=\"s3\"}[1m]) / 60) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "(Cache)Opendal Write bytes/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(databend_opendal_bytes_total{service=\"moka\"}[1m]) / 60) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "(s3)opendal_failures_total/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(databend_opendal_failures_total{service='s3'}[1m]) / 60) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "(s3)opendal_errors_total/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(databend_opendal_errors_total{service='s3'}[1m])) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}