{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "databend-query.fullname" . }}
  labels:
    {{- include "databend-query.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "databend-query.fullname" . }}
  selector:
    matchLabels:
      {{- include "databend-query.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.podMonitor.port }}
{{- end }}
